# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MapReduce.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fMapReduce.proto\x12\nmaster_map\"\x1c\n\x0binput_split\x12\r\n\x05input\x18\x01 \x03(\t\"\"\n\x0einput_response\x12\x10\n\x08response\x18\x01 \x01(\t2K\n\x03map\x12\x44\n\x0binputSplits\x12\x17.master_map.input_split\x1a\x1a.master_map.input_response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MapReduce_pb2', globals())
_MAP = DESCRIPTOR.services_by_name['map']

_INPUT_SPLIT = DESCRIPTOR.message_types_by_name['input_split']
input_split = _reflection.GeneratedProtocolMessageType('input_split', (_message.Message,), {
    'DESCRIPTOR': _INPUT_SPLIT,
    '__module__': 'MapReduce_pb2'
})
_sym_db.RegisterMessage(input_split)

_INPUT_RESPONSE = DESCRIPTOR.message_types_by_name['input_response']
input_response = _reflection.GeneratedProtocolMessageType('input_response', (_message.Message,), {
    'DESCRIPTOR': _INPUT_RESPONSE,
    '__module__': 'MapReduce_pb2'
})
_sym_db.RegisterMessage(input_response)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _INPUT_SPLIT._serialized_start = 31
    _INPUT_SPLIT._serialized_end = 59
    _INPUT_RESPONSE._serialized_start = 61
    _INPUT_RESPONSE._serialized_end = 95
    _MAP._serialized_start = 97
    _MAP._serialized_end = 172
# @@protoc_insertion_point(module_scope)
